---

- include_tasks: download.yml
# - include_tasks: configure.yml # to be used for sentry non-default configuration
- include_tasks: install.yml


- name: Create and start services
  community.docker.docker_compose:
    project_src: /opt/sentry