---

- include_tasks: download.yml
- include_tasks: install.yml
- include_tasks: configure.yml
- pause:



- name: Create and start services
  community.docker.docker_compose:
    project_src: /tmp/sentry